// components/navigation.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
import {
  Home,
  TestTube,
  FolderOpen,
  BarChart3,
  Settings,
  Menu,
  Moon,
  Sun,
} from "lucide-react";
import { useTheme } from "next-themes";

interface NavigationProps {
  children: React.ReactNode;
}

const baseNavigation = [
  { name: "Dashboard", href: "/dashboard", icon: Home },
  { name: "Projetos", href: "/projects", icon: FolderOpen },
  { name: "Relatórios", href: "/reports", icon: BarChart3 },
];

export function Navigation({ children }: NavigationProps) {
  const pathname = usePathname();
  const { theme, setTheme } = useTheme();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [navigation, setNavigation] = useState(baseNavigation);
  const [selectedProjectName, setSelectedProjectName] = useState<string | null>(
    null
  );

  useEffect(() => {
    // Verifica se há um projeto selecionado no localStorage
    const projectId = localStorage.getItem("selectedProjectId");
    const projectName = localStorage.getItem("selectedProjectName");

    if (projectId && projectName) {
      setSelectedProjectName(projectName);
      // Adiciona o menu Testes quando há um projeto selecionado
      const testsMenuItem = {
        name: `Testes - ${projectName}`,
        href: "/tests",
        icon: TestTube,
      };

      setNavigation([
        baseNavigation[0], // Dashboard
        baseNavigation[1], // Projetos
        testsMenuItem, // Testes (apenas quando selecionado)
        baseNavigation[2], // Relatórios
      ]);
    } else {
      // Remove o menu Testes se não há projeto selecionado
      setNavigation(baseNavigation);
      setSelectedProjectName(null);
    }
  }, [pathname]);

  // Função para limpar seleção de projeto quando navegar para outras páginas
  const handleNavigation = (href: string) => {
    if (href !== "/tests") {
      localStorage.removeItem("selectedProjectId");
      localStorage.removeItem("selectedProjectName");
      setNavigation(baseNavigation);
      setSelectedProjectName(null);
    }
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Desktop Sidebar */}
      <div className="hidden lg:fixed lg:inset-y-0 lg:z-50 lg:flex lg:w-72 lg:flex-col">
        <div className="flex grow flex-col gap-y-5 overflow-y-auto border-r bg-background px-6 pb-4">
          <div className="flex h-16 shrink-0 items-center">
            <h1 className="text-xl font-bold">Test Automation Hub</h1>
          </div>
          <nav className="flex flex-1 flex-col">
            <ul role="list" className="flex flex-1 flex-col gap-y-7">
              <li>
                <ul role="list" className="-mx-2 space-y-1">
                  {navigation.map((item) => (
                    <li key={item.name}>
                      <Link
                        href={item.href}
                        onClick={() => handleNavigation(item.href)}
                        className={cn(
                          pathname === item.href
                            ? "bg-primary text-primary-foreground"
                            : "text-muted-foreground hover:text-foreground hover:bg-accent",
                          "group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold transition-colors"
                        )}
                      >
                        <item.icon
                          className="h-6 w-6 shrink-0"
                          aria-hidden="true"
                        />
                        {item.name}
                      </Link>
                    </li>
                  ))}
                </ul>
              </li>
              <li className="mt-auto">
                <div className="flex items-center justify-between">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() =>
                      setTheme(theme === "dark" ? "light" : "dark")
                    }
                  >
                    <Sun className="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
                    <Moon className="absolute h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
                    <span className="sr-only">Toggle theme</span>
                  </Button>
                  <Button variant="ghost" size="sm">
                    <Settings className="h-4 w-4" />
                  </Button>
                </div>
              </li>
            </ul>
          </nav>
        </div>
      </div>

      {/* Mobile menu */}
      <Sheet open={mobileMenuOpen} onOpenChange={setMobileMenuOpen}>
        <SheetTrigger asChild>
          <Button
            variant="ghost"
            size="sm"
            className="lg:hidden fixed top-4 left-4 z-50"
          >
            <Menu className="h-6 w-6" />
          </Button>
        </SheetTrigger>
        <SheetContent side="left" className="w-72">
          <div className="flex flex-col h-full">
            <div className="flex h-16 shrink-0 items-center">
              <h1 className="text-xl font-bold">Test Automation Hub</h1>
            </div>
            <nav className="flex flex-1 flex-col mt-5">
              <ul role="list" className="flex flex-1 flex-col gap-y-7">
                <li>
                  <ul role="list" className="-mx-2 space-y-1">
                    {navigation.map((item) => (
                      <li key={item.name}>
                        <Link
                          href={item.href}
                          onClick={() => {
                            handleNavigation(item.href);
                            setMobileMenuOpen(false);
                          }}
                          className={cn(
                            pathname === item.href
                              ? "bg-primary text-primary-foreground"
                              : "text-muted-foreground hover:text-foreground hover:bg-accent",
                            "group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold transition-colors"
                          )}
                        >
                          <item.icon
                            className="h-6 w-6 shrink-0"
                            aria-hidden="true"
                          />
                          {item.name}
                        </Link>
                      </li>
                    ))}
                  </ul>
                </li>
                <li className="mt-auto">
                  <div className="flex items-center justify-between">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() =>
                        setTheme(theme === "dark" ? "light" : "dark")
                      }
                    >
                      <Sun className="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
                      <Moon className="absolute h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
                    </Button>
                    <Button variant="ghost" size="sm">
                      <Settings className="h-4 w-4" />
                    </Button>
                  </div>
                </li>
              </ul>
            </nav>
          </div>
        </SheetContent>
      </Sheet>

      {/* Main content */}
      <div className="lg:pl-72">
        <main className="py-6 px-4 sm:px-6 lg:px-8">{children}</main>
      </div>
    </div>
  );
}

// src/components/Navigation.vue
<script setup lang="ts">
defineOptions({ name: 'AppNavigation' })
import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import Button from './ui/Button.vue'
import {
  LayoutDashboard,
  FolderOpen,
  FileText,
  TestTube,
  Sun,
  Moon,
  Settings,
} from 'lucide-vue-next'

const router = useRouter()
const route = useRoute()
const isDark = ref(false)

const navigation = [
  { name: 'Dashboard', href: '/', icon: LayoutDashboard, current: false },
  { name: 'Projetos', href: '/projects', icon: FolderOpen, current: false },
  { name: 'Relatórios', href: '/reports', icon: FileText, current: false },
  { name: 'Testes', href: '/tests', icon: TestTube, current: false },
]

const isCurrentRoute = (href: string) => {
  if (href === '/' && route.name === 'dashboard') return true
  return route.path === href
}

const navigateTo = (href: string) => {
  router.push(href)
}

const toggleTheme = () => {
  isDark.value = !isDark.value
  // Adicionar lógica para aplicar o tema ao documento
  //...
  document.documentElement.classList.toggle('dark', isDark.value)
}
</script>

<template>
  <div class="min-h-screen bg-background">
    <div className="hidden lg:fixed lg:inset-y-0 lg:z-50 lg:flex lg:w-72 lg:flex-col">
      <div className="flex grow flex-col gap-y-5 overflow-y-auto border-r bg-background px-6 pb-4">
        <!-- Name App -->
        <div className="flex h-16 shrink-0 items-center">
          <h1 className="text-xl font-bold">Test Automation Hub</h1>
        </div>

        <!-- Menus -->
        <nav className="flex flex-1 flex-col">
          <ul role="list" className="flex flex-1 flex-col gap-y-7">
            <li>
              <ul role="list" className="-mx-2 space-y-1">
                <li v-for="item in navigation" :key="item.name">
                  <Button
                    :class="[
                      'flex items-center gap-x-3 w-full text-left',
                      { 'bg-accent text-accent-foreground': isCurrentRoute(item.href) },
                    ]"
                    @click="navigateTo(item.href)"
                  >
                    <component :is="item.icon" class="h-6 w-6" />
                    <span class="text-sm font-medium">{{ item.name }}</span>
                  </Button>
                </li>
              </ul>
            </li>

            <!-- Footer Nav Bar -->
            <li className="mt-auto">
              <div className="flex items-center justify-between">
                <Button variant="ghost" size="sm" @click="toggleTheme">
                  <Sun
                    v-if="!isDark"
                    class="h-4 w-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0"
                  />
                  <Moon
                    v-else
                    class="absolute h-4 w-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100"
                  />
                </Button>
                <Button variant="ghost" size="sm">
                  <Settings class="h-4 w-4" />
                </Button>
              </div>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</template>

<style scoped>
.transition-transform {
  transition-property: transform;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration: 300ms;
}
</style>
